[package]
name = "genetic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
rand = "0.8.5"
simple_logger = "4.0.0"
clap = { version = "4.1.6", features = ["derive"] }
