[package]
name = "knapsack"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
indicatif = "0.17.3"
bitvec = "1"
rand = "0.8.4"
benchmarking = "0.4.12"
