[package]
name = "genetic"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
rand = "0.8.5"
rayon = "1.7.0"
ctrlc = "3.2.5"
indicatif = "0.17.3"
simple_logger = "4.0.0"
clap = { version = "4.1.6", features = ["derive"] }
